// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: constant_identifier_names, camel_case_types

import 'dart:ffi' as ffi;

const int NULL = 0;

typedef GoInt = GoInt64;

typedef GoInt64 = ffi.Int64;

typedef GoString = _GoString_;

typedef ptrdiff_t = ffi.Int64;

class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}
class max_align_t extends ffi.Opaque {}
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  late final _helloWorldPtr =
      _lookup<ffi.NativeFunction<GoString Function()>>('helloWorld');

  late final _helloWorld = _helloWorldPtr.asFunction<GoString Function()>();

  late final _getUidPtr =
      _lookup<ffi.NativeFunction<GoInt Function()>>('getUid');

  late final _getUid = _getUidPtr.asFunction<int Function()>();
  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int getUid() {
    return _getUid();
  }
  GoString helloWorld() {
    return _helloWorld();
  }
}

class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Int8> p;

  @ptrdiff_t()
  external int n;
}
