# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: dart pub get
      - name: Download llvm
        run: sudo apt-get install libclang-dev
      - name: Get Gozxing
        run: go get github.com/makiuchi-d/gozxing
      - name: Build Go shared library
        run: go build -buildmode=c-shared -o libmain.so main.go
      - name: generate
        run: dart run ffigen
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: binding
         path: generated_bindings.dart
      - name: Upload to Artifacts shared
        uses: actions/upload-artifact@v2
        with:
         name: shared
         path: libmain.so
